name: CI/CD Pipeline for NestJS App on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          known_hosts: ${{ secrets.AWS_EC2_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          set -e  # Exit immediately if a command fails

          cd /var/www/nestjs_sandbox

          echo "Pulling latest changes..."
          git reset --hard  # Prevent merge conflicts
          git pull --prune origin main

          echo "Rebuilding Docker containers..."
          docker-compose up --build --force-recreate -d

          echo "Deployment successful!"
          EOF
